// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnm_sUbQVmAa6qDgKH0YGG9_2FfmBLsuk',
    appId: '1:63287027824:web:f6089dc134e202c1706cb5',
    messagingSenderId: '63287027824',
    projectId: 'quiz-app-8ed13',
    authDomain: 'quiz-app-8ed13.firebaseapp.com',
    storageBucket: 'quiz-app-8ed13.appspot.com',
    measurementId: 'G-S3ZPWJYD35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdBE6NfDCK9Npg0uxKT35O6zDaJZfXlyc',
    appId: '1:63287027824:android:91147935a62377df706cb5',
    messagingSenderId: '63287027824',
    projectId: 'quiz-app-8ed13',
    storageBucket: 'quiz-app-8ed13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWOTQyECfkzXInhKqvAaZ44O4hStWt0rY',
    appId: '1:63287027824:ios:9cc4279b7e86a77e706cb5',
    messagingSenderId: '63287027824',
    projectId: 'quiz-app-8ed13',
    storageBucket: 'quiz-app-8ed13.appspot.com',
    iosBundleId: 'com.example.mcqsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWOTQyECfkzXInhKqvAaZ44O4hStWt0rY',
    appId: '1:63287027824:ios:9cc4279b7e86a77e706cb5',
    messagingSenderId: '63287027824',
    projectId: 'quiz-app-8ed13',
    storageBucket: 'quiz-app-8ed13.appspot.com',
    iosBundleId: 'com.example.mcqsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnm_sUbQVmAa6qDgKH0YGG9_2FfmBLsuk',
    appId: '1:63287027824:web:af3c90e3757b0b2d706cb5',
    messagingSenderId: '63287027824',
    projectId: 'quiz-app-8ed13',
    authDomain: 'quiz-app-8ed13.firebaseapp.com',
    storageBucket: 'quiz-app-8ed13.appspot.com',
    measurementId: 'G-990T258LNG',
  );
}
